"""empty message

Revision ID: 34158b4aafb9
Revises: 536e84635828
Create Date: 2017-04-21 17:13:19.080838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34158b4aafb9'
down_revision = '536e84635828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bucketlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bucketlists')
    # ### end Alembic commands ###
