"""empty message

Revision ID: 536e84635828
Revises: 
Create Date: 2017-04-19 19:14:04.966795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '536e84635828'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bucketlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bucketlists')
    # ### end Alembic commands ###
