"""empty message

Revision ID: 73beacc46259
Revises: b8c60d4856cc
Create Date: 2017-04-25 13:29:08.248171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73beacc46259'
down_revision = 'b8c60d4856cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bucketlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bucketlists')
    # ### end Alembic commands ###
